import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link className="text-white" href="/login">Login</Link>
      <Link className="text-white" href="/register">Register</Link>
      <Link className="text-white" href="/dashboard">Dashboard</Link>
      <Link className="text-white" href="/learn">Learn</Link>
    </div>
  )
}

export default Home
